# -*- coding: utf-8 -*-
"""app.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YahsLVRFqC3andzWDs0oaQnpmcKdnUd0
"""

import streamlit as st
import pickle
import pandas as pd
import time

# Load model
with open('movie_model.pkl','rb') as f:
    cosine_sim = pickle.load(f)

# Sample dataset
data = {
    'Title': ['Toy Story','Inception','The Matrix','Titanic','Avatar'],
    'Genres': ['Animation|Comedy','Action|Sci-Fi','Action|Sci-Fi','Romance|Drama','Action|Adventure'],
    'Keywords': ['toys|friendship','dream|subconscious','virtual|reality','ship|love','pandora|future'],
    'Rating':[8.3,8.8,8.7,7.8,7.9]
}
df = pd.DataFrame(data)
df['features'] = df['Genres'] + ' ' + df['Keywords']

# Recommendation function
def recommend(movie_title):
    if movie_title not in df['Title'].values:
        return ['Movie not found!']
    idx = df[df['Title']==movie_title].index[0]
    sim_scores = list(enumerate(cosine_sim[idx]))
    sim_scores = sorted(sim_scores, key=lambda x:x[1], reverse=True)
    recommended = [df['Title'][i[0]] for i in sim_scores[1:4]]  # top 3
    return recommended

# Streamlit App
st.title('🎬 Movie Recommendation System')
movie_name = st.text_input("Enter a movie name:")
if st.button('Recommend'):
    rec = recommend(movie_name)
    st.success("Recommended Movies:")
    for i in rec:
        st.write(i)

st.markdown('**Designed and Developed by: Anchal**')

